# Generated by Django 4.1.3 on 2022-12-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(default='', max_length=18)),
                ('gender', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('school', models.CharField(max_length=256)),
                ('major', models.CharField(max_length=256)),
                ('degree', models.IntegerField(default=0)),
            ],
        ),
    ]
